#!/usr/bin/env bash

# This script executes the already compiled package using the packages class files
# Usage: ./execute

source settings.sh

assertHasCommands java
[ -r "$OUTDIR/$PACKAGE/$MAIN_CLASS.class" ] || fatalError "you must compile '$PACKAGE' before executing"

EXECUTECOMMAND=$( echo java --module-path $JAVAFX --add-modules $MODULES --class-path $OUTDIR $PACKAGE.$MAIN_CLASS )
echo $EXECUTECOMMAND
$EXECUTECOMMAND || fatalError "returned with exit code $?"


# JAR="$OUTDIR/$PACKAGE.jar"
# [ -e $JAR ] || fatalError "'$JAR' does not exist\ncheck ./compile settings"
# java --module-path "$JAVAFX" --add-modules "$MODULES" -jar "$JAR"
